=== simobe-git/lweb/media/collegamenti/xsd/prenotazioni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="prenotazioni">
		<xsd:complexType> 
			<xsd:sequence>
				<xsd:element ref="singolaPrenotazione" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="singolaPrenotazione">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="dataPrenotazione" minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="tribuna" minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="username" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
			<xsd:attribute name="pagamentoEffettuato" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="N"/>
						<xsd:enumeration value="Y"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="dataPrenotazione" type="xsd:date"/>

	<xsd:element name="tribuna">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nome" minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="numeroPosto" minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="costoPosto" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="nome" type="xsd:string"/>
	<xsd:element name="numeroPosto" type="xsd:string"/>
	<xsd:element name="costoPosto" type="xsd:decimal"/>
	<xsd:element name="username" type="xsd:string"/>

</xsd:schema>

=== simobe-git/lweb/media/collegamenti/xml/prenotazioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<prenotazioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/prenotazioni.xsd">
  <singolaPrenotazione pagamentoEffettuato="N">
    <dataPrenotazione>2025-01-18</dataPrenotazione>
    <tribuna>
      <nome>Roggio</nome>
      <numeroPosto>44</numeroPosto>
      <costoPosto>69.99</costoPosto>
    </tribuna>
    <username>AAA</username>
  </singolaPrenotazione>
  <singolaPrenotazione pagamentoEffettuato="N">
    <dataPrenotazione>2025-01-18</dataPrenotazione>
    <tribuna>
      <nome>Tribuna 21</nome>
      <numeroPosto>22</numeroPosto>
      <costoPosto>29.99</costoPosto>
    </tribuna>
    <username>AAA</username>
  </singolaPrenotazione>
  <singolaPrenotazione pagamentoEffettuato="N">
    <dataPrenotazione>2025-01-18</dataPrenotazione>
    <tribuna>
      <nome>Tribuna 21</nome>
      <numeroPosto>33</numeroPosto>
      <costoPosto>29.99</costoPosto>
    </tribuna>
    <username>abc123</username>
  </singolaPrenotazione>
  <singolaPrenotazione pagamentoEffettuato="N">
    <dataPrenotazione>2025-01-18</dataPrenotazione>
    <tribuna>
      <nome>Ascari 1</nome>
      <numeroPosto>11</numeroPosto>
      <costoPosto>65.49</costoPosto>
    </tribuna>
    <username>AAA</username>
  </singolaPrenotazione>
  <singolaPrenotazione pagamentoEffettuato="N">
    <dataPrenotazione>2025-01-18</dataPrenotazione>
    <tribuna>
      <nome>Tribuna 21</nome>
      <numeroPosto>30</numeroPosto>
      <costoPosto>29.99</costoPosto>
    </tribuna>
    <username>lweb!</username>
  </singolaPrenotazione>
</prenotazioni>
